### ISSUE TITLE
偶尔会出现一个主题出现两次的情况

### ISSUE THREAD

**Issue by VShawn** [curiositytong/hot-list#2]
![baidushurufa_2018-12-24_11-10-58](https://user-images.githubusercontent.com/10143738/50390040-cb4a0900-076c-11e9-9b5c-08e1993c7b71.png)

**Comment by curiositytong** [comment]
@VShawn 感谢指出！之前也有不少人反馈过这个问题，等我空的时候就改掉

**Comment by curiositytong** [comment]
已修复
